# Data Prep

## Reshaping Data

In [66]:
import pandas as pd
import numpy as np

In [67]:
songs_dict = {
                'Customer': ['Aria', 'Aria', 'Aria', 'Chord', 'Chord', 'Harmony', 'Harmony', 'Harmony', 'Melody', 'Reed'],
                'Genre': ['Pop', 'Indie', 'Rock', 'Pop', 'Indie', 'Pop', 'Indie', 'Rock', 'Rock', 'Rock'],
                '# Songs': [50, 48, 1, 15, 36, 10, 5, 3, 2, 5]
             }

df = pd.DataFrame(songs_dict)
df

  Customer  Genre  # Songs
0     Aria    Pop       50
1     Aria  Indie       48
2     Aria   Rock        1
3    Chord    Pop       15
4    Chord  Indie       36
5  Harmony    Pop       10
6  Harmony  Indie        5
7  Harmony   Rock        3
8   Melody   Rock        2
9     Reed   Rock        5

In [68]:
# groub by
(df.groupby(["Customer"])
   .agg(
       TotalNumSong =('# Songs', 'sum')
       )
   .reset_index())

  Customer  TotalNumSong
0     Aria            99
1    Chord            51
2  Harmony            18
3   Melody             2
4     Reed             5

In [69]:
customers_songs = (df.groupby(["Customer"])
                     .agg(TotalNumSong =('# Songs', 'sum'))
                     .reset_index()
                  )

In [70]:
customers_songs

  Customer  TotalNumSong
0     Aria            99
1    Chord            51
2  Harmony            18
3   Melody             2
4     Reed             5

In [71]:
# pivot
(df.pivot(index=['Customer'], columns=['Genre'], values='# Songs')
   .fillna(0)
   .reset_index()
)

Genre Customer  Indie   Pop  Rock
0         Aria   48.0  50.0   1.0
1        Chord   36.0  15.0   0.0
2      Harmony    5.0  10.0   3.0
3       Melody    0.0   0.0   2.0
4         Reed    0.0   0.0   5.0

In [72]:
customers_genres = (
    df.pivot(index=['Customer'], columns=['Genre'], values='# Songs')
   .fillna(0)
   .reset_index()
)

In [73]:
customers_genres

Genre Customer  Indie   Pop  Rock
0         Aria   48.0  50.0   1.0
1        Chord   36.0  15.0   0.0
2      Harmony    5.0  10.0   3.0
3       Melody    0.0   0.0   2.0
4         Reed    0.0   0.0   5.0

## Missing Data

In [74]:
customers_raw = pd.read_csv('../Data/customers.csv')
customers_raw.head(10)

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena   NaN        1.0   $62,000       8/26/23       No          College
6  Stefani   NaN        NaN   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [75]:
customers_raw.shape

(8, 7)

In [76]:
customers_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8 non-null      object
 1   Age              6 non-null      float64
 2   Followers        5 non-null      float64
 3   Income           8 non-null      object
 4   Sign Up Date     8 non-null      object
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: float64(2), object(5)
memory usage: 580.0+ bytes

In [77]:
customers_raw.isna()

    Name    Age  Followers  Income  Sign Up Date  Discount  Education Level
0  False  False      False   False         False     False            False
1  False  False      False   False         False     False            False
2  False  False       True   False         False     False            False
3  False  False       True   False         False     False            False
4  False  False      False   False         False     False            False
5  False   True      False   False         False     False            False
6  False   True       True   False         False     False            False
7  False  False      False   False         False     False            False

In [78]:
customers_raw.isna().any(axis=1)

0    False
1    False
2     True
3     True
4    False
5     True
6     True
7    False
dtype: bool

In [79]:
customers_raw[customers_raw.isna().any(axis=1)]

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
5   Selena   NaN        1.0   $62,000       8/26/23       No          College
6  Stefani   NaN        NaN   $81,000       9/24/23       No          College

In [80]:
customers_raw.dropna()

     Name   Age  Followers    Income Sign Up Date Discount Education Level
0    Aria  25.0        0.0  $45,000       5/18/23      Yes         College
1   Chord  19.0       12.0  $28,000       8/23/23      Yes     High School
4    Reed  52.0        0.0  $75,000       6/14/23      Yes     High School
7  Taylor  33.0       52.0  $60,000        9/8/23       No     High School

In [81]:
customers_raw.dropna().reset_index()

,index,Name,Age,Followers,Income,Sign Up Date,Discount,Education Level
0,0,Aria,25.0,0.0,"$45,000",5/18/23,Yes,College
1,1,Chord,19.0,12.0,"$28,000",8/23/23,Yes,High School
2,4,Reed,52.0,0.0,"$75,000",6/14/23,Yes,High School
3,7,Taylor,33.0,52.0,"$60,000",9/8/23,No,High School

In [82]:
customers_raw.dropna().reset_index(drop=True)

     Name   Age  Followers    Income Sign Up Date Discount Education Level
0    Aria  25.0        0.0  $45,000       5/18/23      Yes         College
1   Chord  19.0       12.0  $28,000       8/23/23      Yes     High School
2    Reed  52.0        0.0  $75,000       6/14/23      Yes     High School
3  Taylor  33.0       52.0  $60,000        9/8/23       No     High School

In [83]:
customers_raw.dropna(axis=1)

      Name     Income Sign Up Date Discount  Education Level
0     Aria   $45,000       5/18/23      Yes          College
1    Chord   $28,000       8/23/23      Yes      High School
2  Harmony  $120,000       4/25/23       No  Graduate School
3   Melody  $450,000        5/5/23       No          College
4     Reed   $75,000       6/14/23      Yes      High School
5   Selena   $62,000       8/26/23       No          College
6  Stefani   $81,000       9/24/23       No          College
7   Taylor   $60,000        9/8/23       No      High School

In [84]:
customers_dropped = customers_raw.dropna().reset_index(drop=True)
customers_dropped

     Name   Age  Followers    Income Sign Up Date Discount Education Level
0    Aria  25.0        0.0  $45,000       5/18/23      Yes         College
1   Chord  19.0       12.0  $28,000       8/23/23      Yes     High School
2    Reed  52.0        0.0  $75,000       6/14/23      Yes     High School
3  Taylor  33.0       52.0  $60,000        9/8/23       No     High School

In [85]:
customers_raw

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena   NaN        1.0   $62,000       8/26/23       No          College
6  Stefani   NaN        NaN   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [86]:
customers = customers_raw.copy()

In [87]:
customers

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena   NaN        1.0   $62,000       8/26/23       No          College
6  Stefani   NaN        NaN   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [88]:
customers.Age.median()

np.float64(29.5)

In [89]:
customers['Age'] = customers.Age.fillna(round(customers.Age.median()))

In [90]:
customers

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena  30.0        1.0   $62,000       8/26/23       No          College
6  Stefani  30.0        NaN   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [91]:
customers['Followers'] = customers.Followers.fillna(0)

In [92]:
customers

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        0.0  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        0.0  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena  30.0        1.0   $62,000       8/26/23       No          College
6  Stefani  30.0        0.0   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [93]:
customers['Age'] = customers.Age.astype('int')

In [94]:
customers

      Name  Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria   25        0.0   $45,000       5/18/23      Yes          College
1    Chord   19       12.0   $28,000       8/23/23      Yes      High School
2  Harmony   26        0.0  $120,000       4/25/23       No  Graduate School
3   Melody   47        0.0  $450,000        5/5/23       No          College
4     Reed   52        0.0   $75,000       6/14/23      Yes      High School
5   Selena   30        1.0   $62,000       8/26/23       No          College
6  Stefani   30        0.0   $81,000       9/24/23       No          College
7   Taylor   33       52.0   $60,000        9/8/23       No      High School

## Convert Data Type

In [95]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8 non-null      object
 1   Age              8 non-null      int64
 2   Followers        8 non-null      float64
 3   Income           8 non-null      object
 4   Sign Up Date     8 non-null      object
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: float64(1), int64(1), object(5)
memory usage: 580.0+ bytes

In [96]:
customers

      Name  Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria   25        0.0   $45,000       5/18/23      Yes          College
1    Chord   19       12.0   $28,000       8/23/23      Yes      High School
2  Harmony   26        0.0  $120,000       4/25/23       No  Graduate School
3   Melody   47        0.0  $450,000        5/5/23       No          College
4     Reed   52        0.0   $75,000       6/14/23      Yes      High School
5   Selena   30        1.0   $62,000       8/26/23       No          College
6  Stefani   30        0.0   $81,000       9/24/23       No          College
7   Taylor   33       52.0   $60,000        9/8/23       No      High School

In [97]:
customers['Income'] = pd.to_numeric(customers.Income.str.replace('$', '').str.replace(',', ''))

In [98]:
customers

      Name  Age  Followers  Income Sign Up Date Discount  Education Level
0     Aria   25        0.0   45000      5/18/23      Yes          College
1    Chord   19       12.0   28000      8/23/23      Yes      High School
2  Harmony   26        0.0  120000      4/25/23       No  Graduate School
3   Melody   47        0.0  450000       5/5/23       No          College
4     Reed   52        0.0   75000      6/14/23      Yes      High School
5   Selena   30        1.0   62000      8/26/23       No          College
6  Stefani   30        0.0   81000      9/24/23       No          College
7   Taylor   33       52.0   60000       9/8/23       No      High School

In [99]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8 non-null      object
 1   Age              8 non-null      int64
 2   Followers        8 non-null      float64
 3   Income           8 non-null      int64
 4   Sign Up Date     8 non-null      object
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 580.0+ bytes

In [100]:
customers['Followers'] = customers.Followers.astype('int64')

In [101]:
customers

      Name  Age  Followers  Income Sign Up Date Discount  Education Level
0     Aria   25          0   45000      5/18/23      Yes          College
1    Chord   19         12   28000      8/23/23      Yes      High School
2  Harmony   26          0  120000      4/25/23       No  Graduate School
3   Melody   47          0  450000       5/5/23       No          College
4     Reed   52          0   75000      6/14/23      Yes      High School
5   Selena   30          1   62000      8/26/23       No          College
6  Stefani   30          0   81000      9/24/23       No          College
7   Taylor   33         52   60000       9/8/23       No      High School

In [102]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8 non-null      object
 1   Age              8 non-null      int64
 2   Followers        8 non-null      int64
 3   Income           8 non-null      int64
 4   Sign Up Date     8 non-null      object
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: int64(3), object(4)
memory usage: 580.0+ bytes

In [103]:
customers

      Name  Age  Followers  Income Sign Up Date Discount  Education Level
0     Aria   25          0   45000      5/18/23      Yes          College
1    Chord   19         12   28000      8/23/23      Yes      High School
2  Harmony   26          0  120000      4/25/23       No  Graduate School
3   Melody   47          0  450000       5/5/23       No          College
4     Reed   52          0   75000      6/14/23      Yes      High School
5   Selena   30          1   62000      8/26/23       No          College
6  Stefani   30          0   81000      9/24/23       No          College
7   Taylor   33         52   60000       9/8/23       No      High School

In [104]:
customers['Sign Up Date'] = pd.to_datetime(customers['Sign Up Date'], format='%m/%d/%y')

In [105]:
customers

      Name  Age  Followers  Income Sign Up Date Discount  Education Level
0     Aria   25          0   45000   2023-05-18      Yes          College
1    Chord   19         12   28000   2023-08-23      Yes      High School
2  Harmony   26          0  120000   2023-04-25       No  Graduate School
3   Melody   47          0  450000   2023-05-05       No          College
4     Reed   52          0   75000   2023-06-14      Yes      High School
5   Selena   30          1   62000   2023-08-26       No          College
6  Stefani   30          0   81000   2023-09-24       No          College
7   Taylor   33         52   60000   2023-09-08       No      High School

In [106]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8 non-null      object
 1   Age              8 non-null      int64
 2   Followers        8 non-null      int64
 3   Income           8 non-null      int64
 4   Sign Up Date     8 non-null      datetime64[ns]
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 580.0+ bytes

## Extract Date Time

In [107]:
customers['Sign Up Month'] = customers['Sign Up Date'].dt.month

In [108]:
customers

,Name,Age,Followers,Income,Sign Up Date,Discount,Education Level,Sign Up Month
0,Aria,25,0,45000,2023-05-18,Yes,College,5
1,Chord,19,12,28000,2023-08-23,Yes,High School,8
2,Harmony,26,0,120000,2023-04-25,No,Graduate School,4
3,Melody,47,0,450000,2023-05-05,No,College,5
4,Reed,52,0,75000,2023-06-14,Yes,High School,6
5,Selena,30,1,62000,2023-08-26,No,College,8
6,Stefani,30,0,81000,2023-09-24,No,College,9
7,Taylor,33,52,60000,2023-09-08,No,High School,9

In [109]:
customers['Sign Up Day'] = customers['Sign Up Date'].dt.dayofweek

In [110]:
customers

,Name,Age,Followers,Income,Sign Up Date,Discount,Education Level,Sign Up Month,Sign Up Day
0,Aria,25,0,45000,2023-05-18,Yes,College,5,3
1,Chord,19,12,28000,2023-08-23,Yes,High School,8,2
2,Harmony,26,0,120000,2023-04-25,No,Graduate School,4,1
3,Melody,47,0,450000,2023-05-05,No,College,5,4
4,Reed,52,0,75000,2023-06-14,Yes,High School,6,2
5,Selena,30,1,62000,2023-08-26,No,College,8,5
6,Stefani,30,0,81000,2023-09-24,No,College,9,6
7,Taylor,33,52,60000,2023-09-08,No,High School,9,4

In [111]:
customers = customers.drop(columns=['Sign Up Date'])

In [112]:
customers

,Name,Age,Followers,Income,Discount,Education Level,Sign Up Month,Sign Up Day
0,Aria,25,0,45000,Yes,College,5,3
1,Chord,19,12,28000,Yes,High School,8,2
2,Harmony,26,0,120000,No,Graduate School,4,1
3,Melody,47,0,450000,No,College,5,4
4,Reed,52,0,75000,Yes,High School,6,2
5,Selena,30,1,62000,No,College,8,5
6,Stefani,30,0,81000,No,College,9,6
7,Taylor,33,52,60000,No,High School,9,4

## Calculating Based on a Condition

In [113]:
np.where(customers['Discount'] == 'Yes', 1, 0)

array([1, 1, 0, 0, 1, 0, 0, 0])

In [114]:
customers['Discount'] = np.where(customers['Discount'] == 'Yes', 1, 0)

In [115]:
customers

,Name,Age,Followers,Income,Discount,Education Level,Sign Up Month,Sign Up Day
0,Aria,25,0,45000,1,College,5,3
1,Chord,19,12,28000,1,High School,8,2
2,Harmony,26,0,120000,0,Graduate School,4,1
3,Melody,47,0,450000,0,College,5,4
4,Reed,52,0,75000,1,High School,6,2
5,Selena,30,1,62000,0,College,8,5
6,Stefani,30,0,81000,0,College,9,6
7,Taylor,33,52,60000,0,High School,9,4

## Dummy Variables

In [116]:
customers['Education Level'].value_counts()

Education Level
College            4
High School        3
Graduate School    1
Name: count, dtype: int64

In [118]:
pd.get_dummies(customers['Education Level']).astype('int64')

   College  Graduate School  High School
0        1                0            0
1        0                0            1
2        0                1            0
3        1                0            0
4        0                0            1
5        1                0            0
6        1                0            0
7        0                0            1

In [119]:
dummies_edu = pd.get_dummies(customers['Education Level']).astype('int64')

In [120]:
dummies_edu

   College  Graduate School  High School
0        1                0            0
1        0                0            1
2        0                1            0
3        1                0            0
4        0                0            1
5        1                0            0
6        1                0            0
7        0                0            1

In [121]:
customers

,Name,Age,Followers,Income,Discount,Education Level,Sign Up Month,Sign Up Day
0,Aria,25,0,45000,1,College,5,3
1,Chord,19,12,28000,1,High School,8,2
2,Harmony,26,0,120000,0,Graduate School,4,1
3,Melody,47,0,450000,0,College,5,4
4,Reed,52,0,75000,1,High School,6,2
5,Selena,30,1,62000,0,College,8,5
6,Stefani,30,0,81000,0,College,9,6
7,Taylor,33,52,60000,0,High School,9,4

In [122]:
pd.concat([customers, dummies_edu], axis=1)

,Name,Age,Followers,Income,Discount,Education Level,Sign Up Month,Sign Up Day,College,Graduate School,High School
0,Aria,25,0,45000,1,College,5,3,1,0,0
1,Chord,19,12,28000,1,High School,8,2,0,0,1
2,Harmony,26,0,120000,0,Graduate School,4,1,0,1,0
3,Melody,47,0,450000,0,College,5,4,1,0,0
4,Reed,52,0,75000,1,High School,6,2,0,0,1
5,Selena,30,1,62000,0,College,8,5,1,0,0
6,Stefani,30,0,81000,0,College,9,6,1,0,0
7,Taylor,33,52,60000,0,High School,9,4,0,0,1

In [123]:
customers = pd.concat([customers, dummies_edu], axis=1)
customers

,Name,Age,Followers,Income,Discount,Education Level,Sign Up Month,Sign Up Day,College,Graduate School,High School
0,Aria,25,0,45000,1,College,5,3,1,0,0
1,Chord,19,12,28000,1,High School,8,2,0,0,1
2,Harmony,26,0,120000,0,Graduate School,4,1,0,1,0
3,Melody,47,0,450000,0,College,5,4,1,0,0
4,Reed,52,0,75000,1,High School,6,2,0,0,1
5,Selena,30,1,62000,0,College,8,5,1,0,0
6,Stefani,30,0,81000,0,College,9,6,1,0,0
7,Taylor,33,52,60000,0,High School,9,4,0,0,1

In [124]:
customers.drop(columns=['Education Level'])

,Name,Age,Followers,Income,Discount,Sign Up Month,Sign Up Day,College,Graduate School,High School
0,Aria,25,0,45000,1,5,3,1,0,0
1,Chord,19,12,28000,1,8,2,0,0,1
2,Harmony,26,0,120000,0,4,1,0,1,0
3,Melody,47,0,450000,0,5,4,1,0,0
4,Reed,52,0,75000,1,6,2,0,0,1
5,Selena,30,1,62000,0,8,5,1,0,0
6,Stefani,30,0,81000,0,9,6,1,0,0
7,Taylor,33,52,60000,0,9,4,0,0,1

In [125]:
customers = customers.drop(columns=['Education Level'])

In [126]:
customers

,Name,Age,Followers,Income,Discount,Sign Up Month,Sign Up Day,College,Graduate School,High School
0,Aria,25,0,45000,1,5,3,1,0,0
1,Chord,19,12,28000,1,8,2,0,0,1
2,Harmony,26,0,120000,0,4,1,0,1,0
3,Melody,47,0,450000,0,5,4,1,0,0
4,Reed,52,0,75000,1,6,2,0,0,1
5,Selena,30,1,62000,0,8,5,1,0,0
6,Stefani,30,0,81000,0,9,6,1,0,0
7,Taylor,33,52,60000,0,9,4,0,0,1