# Data Prep

## Reshaping Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
songs_dict = {
                'Customer': ['Aria', 'Aria', 'Aria', 'Chord', 'Chord', 'Harmony', 'Harmony', 'Harmony', 'Melody', 'Reed'],
                'Genre': ['Pop', 'Indie', 'Rock', 'Pop', 'Indie', 'Pop', 'Indie', 'Rock', 'Rock', 'Rock'],
                '# Songs': [50, 48, 1, 15, 36, 10, 5, 3, 2, 5]
             }

df = pd.DataFrame(songs_dict)
df

  Customer  Genre  # Songs
0     Aria    Pop       50
1     Aria  Indie       48
2     Aria   Rock        1
3    Chord    Pop       15
4    Chord  Indie       36
5  Harmony    Pop       10
6  Harmony  Indie        5
7  Harmony   Rock        3
8   Melody   Rock        2
9     Reed   Rock        5

In [3]:
# groub by
(df.groupby(["Customer"])
   .agg(
       TotalNumSong =('# Songs', 'sum')
       )
   .reset_index())

  Customer  TotalNumSong
0     Aria            99
1    Chord            51
2  Harmony            18
3   Melody             2
4     Reed             5

In [4]:
customers_songs = (df.groupby(["Customer"])
                     .agg(TotalNumSong =('# Songs', 'sum'))
                     .reset_index()
                  )

In [5]:
customers_songs

  Customer  TotalNumSong
0     Aria            99
1    Chord            51
2  Harmony            18
3   Melody             2
4     Reed             5

In [6]:
# pivot
(df.pivot(index=['Customer'], columns=['Genre'], values='# Songs')
   .fillna(0)
   .reset_index()
)

Genre Customer  Indie   Pop  Rock
0         Aria   48.0  50.0   1.0
1        Chord   36.0  15.0   0.0
2      Harmony    5.0  10.0   3.0
3       Melody    0.0   0.0   2.0
4         Reed    0.0   0.0   5.0

In [7]:
customers_genres = (
    df.pivot(index=['Customer'], columns=['Genre'], values='# Songs')
   .fillna(0)
   .reset_index()
)

In [8]:
customers_genres

Genre Customer  Indie   Pop  Rock
0         Aria   48.0  50.0   1.0
1        Chord   36.0  15.0   0.0
2      Harmony    5.0  10.0   3.0
3       Melody    0.0   0.0   2.0
4         Reed    0.0   0.0   5.0

## Missing Data

In [9]:
customers_raw = pd.read_csv('../Data/customers.csv')
customers_raw.head(10)

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena   NaN        1.0   $62,000       8/26/23       No          College
6  Stefani   NaN        NaN   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [10]:
customers_raw.shape

(8, 7)

In [11]:
customers_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8 non-null      object
 1   Age              6 non-null      float64
 2   Followers        5 non-null      float64
 3   Income           8 non-null      object
 4   Sign Up Date     8 non-null      object
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: float64(2), object(5)
memory usage: 580.0+ bytes

In [12]:
customers_raw.isna()

    Name    Age  Followers  Income  Sign Up Date  Discount  Education Level
0  False  False      False   False         False     False            False
1  False  False      False   False         False     False            False
2  False  False       True   False         False     False            False
3  False  False       True   False         False     False            False
4  False  False      False   False         False     False            False
5  False   True      False   False         False     False            False
6  False   True       True   False         False     False            False
7  False  False      False   False         False     False            False

In [13]:
customers_raw.isna().any(axis=1)

0    False
1    False
2     True
3     True
4    False
5     True
6     True
7    False
dtype: bool

In [14]:
customers_raw[customers_raw.isna().any(axis=1)]

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
5   Selena   NaN        1.0   $62,000       8/26/23       No          College
6  Stefani   NaN        NaN   $81,000       9/24/23       No          College

In [15]:
customers_raw.dropna()

     Name   Age  Followers    Income Sign Up Date Discount Education Level
0    Aria  25.0        0.0  $45,000       5/18/23      Yes         College
1   Chord  19.0       12.0  $28,000       8/23/23      Yes     High School
4    Reed  52.0        0.0  $75,000       6/14/23      Yes     High School
7  Taylor  33.0       52.0  $60,000        9/8/23       No     High School

In [16]:
customers_raw.dropna().reset_index()

,index,Name,Age,Followers,Income,Sign Up Date,Discount,Education Level
0,0,Aria,25.0,0.0,"$45,000",5/18/23,Yes,College
1,1,Chord,19.0,12.0,"$28,000",8/23/23,Yes,High School
2,4,Reed,52.0,0.0,"$75,000",6/14/23,Yes,High School
3,7,Taylor,33.0,52.0,"$60,000",9/8/23,No,High School

In [17]:
customers_raw.dropna().reset_index(drop=True)

     Name   Age  Followers    Income Sign Up Date Discount Education Level
0    Aria  25.0        0.0  $45,000       5/18/23      Yes         College
1   Chord  19.0       12.0  $28,000       8/23/23      Yes     High School
2    Reed  52.0        0.0  $75,000       6/14/23      Yes     High School
3  Taylor  33.0       52.0  $60,000        9/8/23       No     High School

In [18]:
customers_raw.dropna(axis=1)

      Name     Income Sign Up Date Discount  Education Level
0     Aria   $45,000       5/18/23      Yes          College
1    Chord   $28,000       8/23/23      Yes      High School
2  Harmony  $120,000       4/25/23       No  Graduate School
3   Melody  $450,000        5/5/23       No          College
4     Reed   $75,000       6/14/23      Yes      High School
5   Selena   $62,000       8/26/23       No          College
6  Stefani   $81,000       9/24/23       No          College
7   Taylor   $60,000        9/8/23       No      High School

In [19]:
customers_dropped = customers_raw.dropna().reset_index(drop=True)
customers_dropped

     Name   Age  Followers    Income Sign Up Date Discount Education Level
0    Aria  25.0        0.0  $45,000       5/18/23      Yes         College
1   Chord  19.0       12.0  $28,000       8/23/23      Yes     High School
2    Reed  52.0        0.0  $75,000       6/14/23      Yes     High School
3  Taylor  33.0       52.0  $60,000        9/8/23       No     High School

In [20]:
customers_raw

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena   NaN        1.0   $62,000       8/26/23       No          College
6  Stefani   NaN        NaN   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [21]:
customers = customers_raw.copy()

In [22]:
customers

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena   NaN        1.0   $62,000       8/26/23       No          College
6  Stefani   NaN        NaN   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [23]:
customers.Age.median()

np.float64(29.5)

In [24]:
customers['Age'] = customers.Age.fillna(round(customers.Age.median()))

In [25]:
customers

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        NaN  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        NaN  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena  30.0        1.0   $62,000       8/26/23       No          College
6  Stefani  30.0        NaN   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [26]:
customers['Followers'] = customers.Followers.fillna(0)

In [27]:
customers

      Name   Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria  25.0        0.0   $45,000       5/18/23      Yes          College
1    Chord  19.0       12.0   $28,000       8/23/23      Yes      High School
2  Harmony  26.0        0.0  $120,000       4/25/23       No  Graduate School
3   Melody  47.0        0.0  $450,000        5/5/23       No          College
4     Reed  52.0        0.0   $75,000       6/14/23      Yes      High School
5   Selena  30.0        1.0   $62,000       8/26/23       No          College
6  Stefani  30.0        0.0   $81,000       9/24/23       No          College
7   Taylor  33.0       52.0   $60,000        9/8/23       No      High School

In [28]:
customers['Age'] = customers.Age.astype('int')

In [29]:
customers

      Name  Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria   25        0.0   $45,000       5/18/23      Yes          College
1    Chord   19       12.0   $28,000       8/23/23      Yes      High School
2  Harmony   26        0.0  $120,000       4/25/23       No  Graduate School
3   Melody   47        0.0  $450,000        5/5/23       No          College
4     Reed   52        0.0   $75,000       6/14/23      Yes      High School
5   Selena   30        1.0   $62,000       8/26/23       No          College
6  Stefani   30        0.0   $81,000       9/24/23       No          College
7   Taylor   33       52.0   $60,000        9/8/23       No      High School

## Convert Data Type

In [30]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8 non-null      object
 1   Age              8 non-null      int64
 2   Followers        8 non-null      float64
 3   Income           8 non-null      object
 4   Sign Up Date     8 non-null      object
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: float64(1), int64(1), object(5)
memory usage: 580.0+ bytes

In [31]:
customers

      Name  Age  Followers     Income Sign Up Date Discount  Education Level
0     Aria   25        0.0   $45,000       5/18/23      Yes          College
1    Chord   19       12.0   $28,000       8/23/23      Yes      High School
2  Harmony   26        0.0  $120,000       4/25/23       No  Graduate School
3   Melody   47        0.0  $450,000        5/5/23       No          College
4     Reed   52        0.0   $75,000       6/14/23      Yes      High School
5   Selena   30        1.0   $62,000       8/26/23       No          College
6  Stefani   30        0.0   $81,000       9/24/23       No          College
7   Taylor   33       52.0   $60,000        9/8/23       No      High School

In [32]:
customers['Income'] = pd.to_numeric(customers.Income.str.replace('$', '').str.replace(',', ''))

In [33]:
customers

      Name  Age  Followers  Income Sign Up Date Discount  Education Level
0     Aria   25        0.0   45000      5/18/23      Yes          College
1    Chord   19       12.0   28000      8/23/23      Yes      High School
2  Harmony   26        0.0  120000      4/25/23       No  Graduate School
3   Melody   47        0.0  450000       5/5/23       No          College
4     Reed   52        0.0   75000      6/14/23      Yes      High School
5   Selena   30        1.0   62000      8/26/23       No          College
6  Stefani   30        0.0   81000      9/24/23       No          College
7   Taylor   33       52.0   60000       9/8/23       No      High School

In [34]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8 non-null      object
 1   Age              8 non-null      int64
 2   Followers        8 non-null      float64
 3   Income           8 non-null      int64
 4   Sign Up Date     8 non-null      object
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 580.0+ bytes

In [35]:
customers['Followers'] = customers.Followers.astype('int64')

In [36]:
customers

      Name  Age  Followers  Income Sign Up Date Discount  Education Level
0     Aria   25          0   45000      5/18/23      Yes          College
1    Chord   19         12   28000      8/23/23      Yes      High School
2  Harmony   26          0  120000      4/25/23       No  Graduate School
3   Melody   47          0  450000       5/5/23       No          College
4     Reed   52          0   75000      6/14/23      Yes      High School
5   Selena   30          1   62000      8/26/23       No          College
6  Stefani   30          0   81000      9/24/23       No          College
7   Taylor   33         52   60000       9/8/23       No      High School

In [37]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8 non-null      object
 1   Age              8 non-null      int64
 2   Followers        8 non-null      int64
 3   Income           8 non-null      int64
 4   Sign Up Date     8 non-null      object
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: int64(3), object(4)
memory usage: 580.0+ bytes

In [38]:
customers

      Name  Age  Followers  Income Sign Up Date Discount  Education Level
0     Aria   25          0   45000      5/18/23      Yes          College
1    Chord   19         12   28000      8/23/23      Yes      High School
2  Harmony   26          0  120000      4/25/23       No  Graduate School
3   Melody   47          0  450000       5/5/23       No          College
4     Reed   52          0   75000      6/14/23      Yes      High School
5   Selena   30          1   62000      8/26/23       No          College
6  Stefani   30          0   81000      9/24/23       No          College
7   Taylor   33         52   60000       9/8/23       No      High School

In [39]:
customers['Sign Up Date'] = pd.to_datetime(customers['Sign Up Date'], format='%m/%d/%y')

In [40]:
customers

      Name  Age  Followers  Income Sign Up Date Discount  Education Level
0     Aria   25          0   45000   2023-05-18      Yes          College
1    Chord   19         12   28000   2023-08-23      Yes      High School
2  Harmony   26          0  120000   2023-04-25       No  Graduate School
3   Melody   47          0  450000   2023-05-05       No          College
4     Reed   52          0   75000   2023-06-14      Yes      High School
5   Selena   30          1   62000   2023-08-26       No          College
6  Stefani   30          0   81000   2023-09-24       No          College
7   Taylor   33         52   60000   2023-09-08       No      High School

In [41]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             8 non-null      object
 1   Age              8 non-null      int64
 2   Followers        8 non-null      int64
 3   Income           8 non-null      int64
 4   Sign Up Date     8 non-null      datetime64[ns]
 5   Discount         8 non-null      object
 6   Education Level  8 non-null      object
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 580.0+ bytes

## Extract Date Time

In [42]:
customers['Sign Up Month'] = customers['Sign Up Date'].dt.month

In [43]:
customers

,Name,Age,Followers,Income,Sign Up Date,Discount,Education Level,Sign Up Month
0,Aria,25,0,45000,2023-05-18,Yes,College,5
1,Chord,19,12,28000,2023-08-23,Yes,High School,8
2,Harmony,26,0,120000,2023-04-25,No,Graduate School,4
3,Melody,47,0,450000,2023-05-05,No,College,5
4,Reed,52,0,75000,2023-06-14,Yes,High School,6
5,Selena,30,1,62000,2023-08-26,No,College,8
6,Stefani,30,0,81000,2023-09-24,No,College,9
7,Taylor,33,52,60000,2023-09-08,No,High School,9

In [44]:
customers['Sign Up DOW'] = customers['Sign Up Date'].dt.dayofweek

In [45]:
customers

,Name,Age,Followers,Income,Sign Up Date,Discount,Education Level,Sign Up Month,Sign Up DOW
0,Aria,25,0,45000,2023-05-18,Yes,College,5,3
1,Chord,19,12,28000,2023-08-23,Yes,High School,8,2
2,Harmony,26,0,120000,2023-04-25,No,Graduate School,4,1
3,Melody,47,0,450000,2023-05-05,No,College,5,4
4,Reed,52,0,75000,2023-06-14,Yes,High School,6,2
5,Selena,30,1,62000,2023-08-26,No,College,8,5
6,Stefani,30,0,81000,2023-09-24,No,College,9,6
7,Taylor,33,52,60000,2023-09-08,No,High School,9,4

In [46]:
customers = customers.drop(columns=['Sign Up Date'])

In [47]:
customers

,Name,Age,Followers,Income,Discount,Education Level,Sign Up Month,Sign Up DOW
0,Aria,25,0,45000,Yes,College,5,3
1,Chord,19,12,28000,Yes,High School,8,2
2,Harmony,26,0,120000,No,Graduate School,4,1
3,Melody,47,0,450000,No,College,5,4
4,Reed,52,0,75000,Yes,High School,6,2
5,Selena,30,1,62000,No,College,8,5
6,Stefani,30,0,81000,No,College,9,6
7,Taylor,33,52,60000,No,High School,9,4

## Calculating Based on a Condition

In [48]:
np.where(customers['Discount'] == 'Yes', 1, 0)

array([1, 1, 0, 0, 1, 0, 0, 0])

In [49]:
customers['Discount'] = np.where(customers['Discount'] == 'Yes', 1, 0)

In [50]:
customers

,Name,Age,Followers,Income,Discount,Education Level,Sign Up Month,Sign Up DOW
0,Aria,25,0,45000,1,College,5,3
1,Chord,19,12,28000,1,High School,8,2
2,Harmony,26,0,120000,0,Graduate School,4,1
3,Melody,47,0,450000,0,College,5,4
4,Reed,52,0,75000,1,High School,6,2
5,Selena,30,1,62000,0,College,8,5
6,Stefani,30,0,81000,0,College,9,6
7,Taylor,33,52,60000,0,High School,9,4

## Dummy Variables

In [51]:
customers['Education Level'].value_counts()

Education Level
College            4
High School        3
Graduate School    1
Name: count, dtype: int64

In [52]:
pd.get_dummies(customers['Education Level']).astype('int64')

   College  Graduate School  High School
0        1                0            0
1        0                0            1
2        0                1            0
3        1                0            0
4        0                0            1
5        1                0            0
6        1                0            0
7        0                0            1

In [53]:
dummies_edu = pd.get_dummies(customers['Education Level']).astype('int64')

In [54]:
dummies_edu

   College  Graduate School  High School
0        1                0            0
1        0                0            1
2        0                1            0
3        1                0            0
4        0                0            1
5        1                0            0
6        1                0            0
7        0                0            1

In [55]:
customers

,Name,Age,Followers,Income,Discount,Education Level,Sign Up Month,Sign Up DOW
0,Aria,25,0,45000,1,College,5,3
1,Chord,19,12,28000,1,High School,8,2
2,Harmony,26,0,120000,0,Graduate School,4,1
3,Melody,47,0,450000,0,College,5,4
4,Reed,52,0,75000,1,High School,6,2
5,Selena,30,1,62000,0,College,8,5
6,Stefani,30,0,81000,0,College,9,6
7,Taylor,33,52,60000,0,High School,9,4

In [56]:
pd.concat([customers, dummies_edu], axis=1)

,Name,Age,Followers,Income,Discount,Education Level,Sign Up Month,Sign Up DOW,College,Graduate School,High School
0,Aria,25,0,45000,1,College,5,3,1,0,0
1,Chord,19,12,28000,1,High School,8,2,0,0,1
2,Harmony,26,0,120000,0,Graduate School,4,1,0,1,0
3,Melody,47,0,450000,0,College,5,4,1,0,0
4,Reed,52,0,75000,1,High School,6,2,0,0,1
5,Selena,30,1,62000,0,College,8,5,1,0,0
6,Stefani,30,0,81000,0,College,9,6,1,0,0
7,Taylor,33,52,60000,0,High School,9,4,0,0,1

In [57]:
customers = pd.concat([customers, dummies_edu], axis=1)
customers

,Name,Age,Followers,Income,Discount,Education Level,Sign Up Month,Sign Up DOW,College,Graduate School,High School
0,Aria,25,0,45000,1,College,5,3,1,0,0
1,Chord,19,12,28000,1,High School,8,2,0,0,1
2,Harmony,26,0,120000,0,Graduate School,4,1,0,1,0
3,Melody,47,0,450000,0,College,5,4,1,0,0
4,Reed,52,0,75000,1,High School,6,2,0,0,1
5,Selena,30,1,62000,0,College,8,5,1,0,0
6,Stefani,30,0,81000,0,College,9,6,1,0,0
7,Taylor,33,52,60000,0,High School,9,4,0,0,1

In [58]:
customers.drop(columns=['Education Level'])

,Name,Age,Followers,Income,Discount,Sign Up Month,Sign Up DOW,College,Graduate School,High School
0,Aria,25,0,45000,1,5,3,1,0,0
1,Chord,19,12,28000,1,8,2,0,0,1
2,Harmony,26,0,120000,0,4,1,0,1,0
3,Melody,47,0,450000,0,5,4,1,0,0
4,Reed,52,0,75000,1,6,2,0,0,1
5,Selena,30,1,62000,0,8,5,1,0,0
6,Stefani,30,0,81000,0,9,6,1,0,0
7,Taylor,33,52,60000,0,9,4,0,0,1

In [59]:
customers = customers.drop(columns=['Education Level'])

In [60]:
customers

,Name,Age,Followers,Income,Discount,Sign Up Month,Sign Up DOW,College,Graduate School,High School
0,Aria,25,0,45000,1,5,3,1,0,0
1,Chord,19,12,28000,1,8,2,0,0,1
2,Harmony,26,0,120000,0,4,1,0,1,0
3,Melody,47,0,450000,0,5,4,1,0,0
4,Reed,52,0,75000,1,6,2,0,0,1
5,Selena,30,1,62000,0,8,5,1,0,0
6,Stefani,30,0,81000,0,9,6,1,0,0
7,Taylor,33,52,60000,0,9,4,0,0,1

## Feature Engineering

In [61]:
# the data from setting the row granularity, with a few more customers
songs_genres_dict = {'Customer': ['Aria', 'Chord', 'Harmony', 'Melody', 'Reed', 'Selena', 'Stefani', 'Taylor'],
                     '# Songs': [99, 51, 18, 2, 5, 60, 15, 121],
                     'Indie': [48, 36, 5, 0, 0, 20, 2, 19],
                     'Pop': [50, 15, 10, 0, 0, 20, 5, 89],
                     'Rock': [1, 0, 3, 2, 5, 20, 8, 13]}

songs_genres = pd.DataFrame(songs_genres_dict)
songs_genres

  Customer  # Songs  Indie  Pop  Rock
0     Aria       99     48   50     1
1    Chord       51     36   15     0
2  Harmony       18      5   10     3
3   Melody        2      0    0     2
4     Reed        5      0    0     5
5   Selena       60     20   20    20
6  Stefani       15      2    5     8
7   Taylor      121     19   89    13

In [62]:
model_df = pd.concat([customers, songs_genres], axis=1).drop(columns=['Customer'])
model_df

,Name,Age,Followers,Income,Discount,Sign Up Month,Sign Up DOW,College,Graduate School,High School,# Songs,Indie,Pop,Rock
0,Aria,25,0,45000,1,5,3,1,0,0,99,48,50,1
1,Chord,19,12,28000,1,8,2,0,0,1,51,36,15,0
2,Harmony,26,0,120000,0,4,1,0,1,0,18,5,10,3
3,Melody,47,0,450000,0,5,4,1,0,0,2,0,0,2
4,Reed,52,0,75000,1,6,2,0,0,1,5,0,0,5
5,Selena,30,1,62000,0,8,5,1,0,0,60,20,20,20
6,Stefani,30,0,81000,0,9,6,1,0,0,15,2,5,8
7,Taylor,33,52,60000,0,9,4,0,0,1,121,19,89,13

In [63]:
model_df.Pop

0    50
1    15
2    10
3     0
4     0
5    20
6     5
7    89
Name: Pop, dtype: int64

In [64]:
model_df['# Songs']

0     99
1     51
2     18
3      2
4      5
5     60
6     15
7    121
Name: # Songs, dtype: int64

In [65]:
model_df['Pct_Pop'] = model_df.Pop / model_df['# Songs']
model_df

,Name,Age,Followers,Income,Discount,Sign Up Month,Sign Up DOW,College,Graduate School,High School,# Songs,Indie,Pop,Rock,Pct_Pop
0,Aria,25,0,45000,1,5,3,1,0,0,99,48,50,1,0.505051
1,Chord,19,12,28000,1,8,2,0,0,1,51,36,15,0,0.294118
2,Harmony,26,0,120000,0,4,1,0,1,0,18,5,10,3,0.555556
3,Melody,47,0,450000,0,5,4,1,0,0,2,0,0,2,0.000000
4,Reed,52,0,75000,1,6,2,0,0,1,5,0,0,5,0.000000
5,Selena,30,1,62000,0,8,5,1,0,0,60,20,20,20,0.333333
6,Stefani,30,0,81000,0,9,6,1,0,0,15,2,5,8,0.333333
7,Taylor,33,52,60000,0,9,4,0,0,1,121,19,89,13,0.735537

In [66]:
np.where(customers['Sign Up DOW'].isin([5,6]), 1,0)

array([0, 0, 0, 0, 0, 1, 1, 0])

In [67]:
model_df['Weekend'] = np.where(customers['Sign Up DOW'].isin([5,6]), 1,0)

In [68]:
model_df

,Name,Age,Followers,Income,Discount,Sign Up Month,Sign Up DOW,College,Graduate School,High School,# Songs,Indie,Pop,Rock,Pct_Pop,Weekend
0,Aria,25,0,45000,1,5,3,1,0,0,99,48,50,1,0.505051,0
1,Chord,19,12,28000,1,8,2,0,0,1,51,36,15,0,0.294118,0
2,Harmony,26,0,120000,0,4,1,0,1,0,18,5,10,3,0.555556,0
3,Melody,47,0,450000,0,5,4,1,0,0,2,0,0,2,0.000000,0
4,Reed,52,0,75000,1,6,2,0,0,1,5,0,0,5,0.000000,0
5,Selena,30,1,62000,0,8,5,1,0,0,60,20,20,20,0.333333,1
6,Stefani,30,0,81000,0,9,6,1,0,0,15,2,5,8,0.333333,1
7,Taylor,33,52,60000,0,9,4,0,0,1,121,19,89,13,0.735537,0

## Identifying Proxy Varaibles

In [69]:
avg_temp_dict = {'Month': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                 'Avg_Temp': [32, 36, 45, 56, 66, 77, 82, 81, 74, 62, 50, 37]}

avg_temp = pd.DataFrame(avg_temp_dict)
avg_temp

    Month  Avg_Temp
0       1        32
1       2        36
2       3        45
3       4        56
4       5        66
5       6        77
6       7        82
7       8        81
8       9        74
9      10        62
10     11        50
11     12        37

In [71]:
model_df = pd.merge(model_df, avg_temp, left_on='Sign Up Month', right_on='Month', how='left')

In [72]:
model_df = model_df.drop(columns=['Month', 'Sign Up Month'])
model_df

,Name,Age,Followers,Income,Discount,Sign Up DOW,College,Graduate School,High School,# Songs,Indie,Pop,Rock,Pct_Pop,Weekend,Avg_Temp
0,Aria,25,0,45000,1,3,1,0,0,99,48,50,1,0.505051,0,66
1,Chord,19,12,28000,1,2,0,0,1,51,36,15,0,0.294118,0,81
2,Harmony,26,0,120000,0,1,0,1,0,18,5,10,3,0.555556,0,56
3,Melody,47,0,450000,0,4,1,0,0,2,0,0,2,0.000000,0,66
4,Reed,52,0,75000,1,2,0,0,1,5,0,0,5,0.000000,0,77
5,Selena,30,1,62000,0,5,1,0,0,60,20,20,20,0.333333,1,81
6,Stefani,30,0,81000,0,6,1,0,0,15,2,5,8,0.333333,1,74
7,Taylor,33,52,60000,0,4,0,0,1,121,19,89,13,0.735537,0,74

## Feature Selection

In [75]:
name = model_df.Name
name

0       Aria
1      Chord
2    Harmony
3     Melody
4       Reed
5     Selena
6    Stefani
7     Taylor
Name: Name, dtype: object

In [77]:
model_df = model_df.drop(columns=['Name'])
model_df

,Age,Followers,Income,Discount,Sign Up DOW,College,Graduate School,High School,# Songs,Indie,Pop,Rock,Pct_Pop,Weekend,Avg_Temp
0,25,0,45000,1,3,1,0,0,99,48,50,1,0.505051,0,66
1,19,12,28000,1,2,0,0,1,51,36,15,0,0.294118,0,81
2,26,0,120000,0,1,0,1,0,18,5,10,3,0.555556,0,56
3,47,0,450000,0,4,1,0,0,2,0,0,2,0.000000,0,66
4,52,0,75000,1,2,0,0,1,5,0,0,5,0.000000,0,77
5,30,1,62000,0,5,1,0,0,60,20,20,20,0.333333,1,81
6,30,0,81000,0,6,1,0,0,15,2,5,8,0.333333,1,74
7,33,52,60000,0,4,0,0,1,121,19,89,13,0.735537,0,74